# Generated by Django 2.2 on 2021-10-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('book_category', models.CharField(max_length=200)),
                ('book_description', models.CharField(max_length=500)),
                ('book_rating', models.FloatField()),
                ('book_image', models.CharField(max_length=500)),
            ],
        ),
    ]
