# Generated by Django 2.2 on 2021-11-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdata',
            name='book_genre',
            field=models.CharField(default='favorites', max_length=200),
        ),
    ]
